pr:
  - main

pool:
  vmImage: 'ubuntu-latest'
  
jobs:
  - job: Lint
    steps:
      - checkout: self
        fetchDepth: 0
      - task: UseDotNet@2
        input:
          version: '8.x'
variables:
  buildConfiguration: 'Release'

