global:
  scrape_interval: 5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.18.0.1:9100']
  - job_name: 'loki-exporter'
    static_configs:
      - targets: [172.18.0.1:3100]