global:
  scrape_interval: 5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['127.0.0.1:9100']
  - job_name: 'loki-exporter'
    static_configs:
      - targets: [loki:3100]
  - job_name: 'recipeAPI'
    static_configs:
      - targets: [127.0.0.1:5022]