apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: nginx-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-service
      tier: replica
  template:
    metadata:
      name: frontend
      labels:
        app: nginx-service
        tier: replica
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.5
