name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag existente para deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código da tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore
        working-directory: src/recipeAPI

      - name: Publicar aplicação
        run: dotnet publish -c Release -o ../../publish
        working-directory: src/recipeAPI

      - name: Deploy para Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: recipeapi
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
